name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop

defaults: &defaults
  run:
    shell: bash
  runs-on: ubuntu-latest


jobs:
  setup-java:
    <<: *defaults
    steps:
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

  build:
    <<: *defaults
    steps:
      - name: Build
        uses: ./.github/workflows/gradle-build.yml
        with:
          job: build
      - run: java --version


  test:
    <<: *defaults
    uses: ./.github/workflows/gradle-test.yml
    with:
      job: test

  package:
    <<: *defaults
    uses: ./.github/workflows/docker-packaging.yml
    with:
      job: package

  deploy:
    <<: *defaults
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ecr-deploy.yml