name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop
defaults:
  run:
    shell: bash


jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

  build:
    uses: ./build/gradle-build.yml@main
    with:
      job: build
    steps:
      run: java --version

  test:
    uses: ./test/gradle-test.yml@main
    with:
      job: test

  package:
    uses: ./packaging/docker-packaging@main
    with:
      job: package

  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./deploy/ecr-deploy.yml@main